ArchiveProject2019/Models/Party.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using ArchiveProject2019.Resources;

namespace ArchiveProject2019.Models
{
    public class Party
    {
        [Key]
        public int Id { get; set; }



        [Required(ErrorMessageResourceType = typeof(main_lang), ErrorMessageResourceName = "PartyNameRequired")]
        [StringLength(maximumLength: 50, MinimumLength = 3, ErrorMessageResourceType = typeof(main_lang), ErrorMessageResourceName = "NameLength")]
        [Display(Name = "PartyName", ResourceType = typeof(main_lang))]
        public string Name { get; set; }



        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy-HH:mm:ss}")]
        [Display(Name = "CreatedAt", ResourceType = typeof(main_lang))]
        public string CreatedAt { get; set; }



        // Relate with User Table For Create By.
        [Display(Name = "CreatedById", ResourceType = typeof(main_lang))]
        public string CreatedById { set; get; }
        [ForeignKey("CreatedById")]
        public ApplicationUser CreatedBy { set; get; }



        [Display(Name = "UpdatedById", ResourceType = typeof(main_lang))]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy-HH:mm:ss}")]
        public string UpdatedAt { get; set; }


        [Display(Name = "UpdatedById", ResourceType = typeof(main_lang))]
        public string UpdatedById { set; get; }
        [ForeignKey("UpdatedById")]
        public ApplicationUser UpdatedBy { set; get; }
        
        
        
        
        // Collections
        public ICollection<Document> Documents { set; get; }
        public ICollection<DocumentParty> DocumentParties { set; get; }
    }
}

ArchiveProject2019/Controllers/PartiesController.cs
using ArchiveProject2019.HelperClasses;
using ArchiveProject2019.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ArchiveProject2019.Controllers
{
    public class PartiesController : Controller
    {
        // GET: Parties
        private ApplicationDbContext _context;

        public PartiesController()
        {
            _context = new ApplicationDbContext();
        }

        
        [AccessDeniedAuthorizeattribute(ActionName = "ConcernedPartiesIndex")]

        public ActionResult Index(string Id = "none")
        {
            if (!Id.Equals("none"))
            {
                ViewBag.Msg = Id;

            }
            else
            {
                ViewBag.Msg = null;
            }

            ViewBag.Current = "Party";
            var parties = _context.Parties.ToList();
            return View(parties.OrderByDescending(a=>a.CreatedAt).ToList());
        }


        
        [AccessDeniedAuthorizeattribute(ActionName = "ConcernedPartiesCreate")]
        public ActionResult Create()
        {

            ViewBag.Current = "Partys";

            return View();
        }

        
        [AccessDeniedAuthorizeattribute(ActionName = "ConcernedPartiesCreate")]
        [HttpPost]
        [ValidateAntiForgeryToken]


        public ActionResult Create([Bind(Include = "Id,Name,CreatedAt")] Party Party)

        {
            ViewBag.Current = "Partys";

            if (_context.Parties.Any(a => a.Name.Equals(Party.Name, StringComparison.OrdinalIgnoreCase)))
            {
                return RedirectToAction("Index", new { Id = "CreateError" });

            }
            if (ModelState.IsValid)
            {
                string NotificationTime = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");

                Party.CreatedAt = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");
                Party.CreatedById = User.Identity.GetUserId();

                _context.Parties.Add(Party);
                _context.SaveChanges();

                string UserId = User.Identity.GetUserId();
                Notification notification = null;
                List<ApplicationUser> Users = _context.Users.Where(a => !a.Id.Equals(UserId)).ToList();
                foreach (ApplicationUser user in Users)
                {

                    notification = new Notification()
                    {

                        CreatedAt = NotificationTime,
                        Active = false,
                        UserId = user.Id,
                        Message = "تم إضافة نوع جديد من الجهات : " + Party.Name,
                        NotificationOwnerId = UserId
                    };
                    _context.Notifications.Add(notification);
                }
                _context.SaveChanges();


                return RedirectToAction("Index", new { Id = "CreateSuccess" });

            }
            return RedirectToAction("Index");

        }


        
        [AccessDeniedAuthorizeattribute(ActionName = "ConcernedPartiesEdit")]
        public ActionResult Edit(int? id)
        {
            ViewBag.Current = "Party";

            if (id == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");
            }

            Party party = _context.Parties.Find(id);
            if (party == null)
            {
            return RedirectToAction("HttpNotFoundError", "ErrorController");

            }
            ViewBag.OldName = party.Name;
            return View(party);
        }

        
        [AccessDeniedAuthorizeattribute(ActionName = "ConcernedPartiesEdit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Party party,string OldName)
        {
            if (_context.Parties.Where(a => a.Id != party.Id).Any(a => a.Name.Equals(party.Name, StringComparison.OrdinalIgnoreCase)))
                return RedirectToAction("Index", new { Id = "EditError" });

            if (ModelState.IsValid)
            {
                party .UpdatedAt= DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");
                string NotificationTime = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");
                party.UpdatedById = User.Identity.GetUserId();

                _context.Entry(party).State = EntityState.Modified;


                _context.SaveChanges();

                string UserId = User.Identity.GetUserId();
                Notification notification = null;
                List<ApplicationUser> Users = _context.Users.Where(a => !a.Id.Equals(UserId)).ToList();
                foreach (ApplicationUser user in Users)
                {

                    notification = new Notification()
                    {

                        CreatedAt = NotificationTime,
                        Active = false,
                        UserId = user.Id,
                        Message = "تم تعديل اسم الجهة من :"+OldName+" إلى الاسم :" + party.Name,
                        NotificationOwnerId = UserId
                    };
                    _context.Notifications.Add(notification);
                }
                _context.SaveChanges();


                return RedirectToAction("Index", new { Id = "EditSuccess" });
            }

            return RedirectToAction("Index");
        }



        
        [AccessDeniedAuthorizeattribute(ActionName = "ConcernedPartiesDelete")]

        public ActionResult Delete(int? id)
        {
            ViewBag.Current = "Party";


            if (id == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");

            }

            Party party = _context.Parties.Find(id);
            if (party == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");

            }

            if (CheckDelete.CheckPartydelete(party.Id) == false)
            {
                return RedirectToAction("Index", new { Id = "DeleteError" });


            }

            return View(party);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        
        [AccessDeniedAuthorizeattribute(ActionName = "ConcernedPartiesDelete")]
        public ActionResult Confirm(int? id)
        {
            ViewBag.Current = "Party";

            Party party = _context.Parties.Find(id);
            string NotificationTime = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");

            _context.Parties.Remove(party);
            _context.SaveChanges();

            string UserId = User.Identity.GetUserId();
            Notification notification = null;
            List<ApplicationUser> Users = _context.Users.Where(a => !a.Id.Equals(UserId)).ToList();
            foreach (ApplicationUser user in Users)
            {

                notification = new Notification()
                {

                    CreatedAt = NotificationTime,
                    Active = false,
                    UserId = user.Id,
                    Message = "تم حذف اسم الجهة  :" + party.Name,
                    NotificationOwnerId = UserId
                };
                _context.Notifications.Add(notification);
            }
            _context.SaveChanges();


            return RedirectToAction("Index", new { Id = "DeleteSuccess" });
        }


        
      [AccessDeniedAuthorizeattribute(ActionName = "ConcernedPartiesDetails")]

        public ActionResult Details(int? id)
        {
            ViewBag.Current = "Party";


            if (id == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");

            }

            Party party = _context.Parties.Include(a=>a.CreatedBy).Include(a=>a.UpdatedBy).SingleOrDefault(a=>a.Id==id);
            if (party == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");

            }

            return View(party);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ArchiveProject2019/Views/Parties/Create.cshtml
@model ArchiveProject2019.Models.Party

@{
    ViewBag.Title = "انشاء جهة";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="modal-footer justify-content-center" style="margin-top:50px">

            <input type="submit" title="إضافة جهة جديدة " value="اضافة جهة جديدة " class="btn btn-primary" />
            <button type="button" title="إغلاق النافذة" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
        </div>


    </div>
}





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArchiveProject2019/Views/Parties/Delete.cshtml
@model ArchiveProject2019.Models.Party

@{
    ViewBag.Title = "حذف الجهة المهتمّة";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



<h3>هل انت متأكد من عملية الحذف؟</h3>
<div>

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="modal-footer justify-content-center" style="margin-top:50px">

            <input type="submit" title="حذف جهة معينة" value="حذف جهة معينة" class="btn btn-danger" />
            <button type="button" title="إغلاق النافذة" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
        </div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArchiveProject2019/Views/Parties/Details.cshtml
@model ArchiveProject2019.Models.Party

@{
    ViewBag.Title = "تفاصيل الجهة ";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>








        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.CreatedById)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy.FullName)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.UpdatedById)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy.FullName)
        </dd>





    </dl>
</div>



<div class="modal-footer justify-content-center" style="margin-top:50px">

    <button type="button" title="إغلاق النافذة" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArchiveProject2019/Views/Parties/Edit.cshtml
@model ArchiveProject2019.Models.Party

@{
    ViewBag.Title = "تعديل الجهة المهتمّة";
    Layout = "~/Views/Shared/_Layout2.cshtml";

}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CreatedAt)
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CreatedAt)
        @Html.Hidden("OldName", (string)ViewBag.OldName)
        @Html.HiddenFor(model => model.CreatedById)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <div class="modal-footer justify-content-center" style="margin-top:50px">

                <input type="submit" title="تعديل حهة معينة" value="تعديل جهة معينة" class="btn btn-success" />
                <button type="button" title="إغلاق النافذة" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArchiveProject2019/Views/Parties/Index.cshtml
@model IEnumerable<ArchiveProject2019.Models.Party>
@using ArchiveProject2019.HelperClasses
@{
    ViewBag.Title = "الجهات المعنية";
    Layout = "~/Views/Shared/_DashBoardLayout.cshtml";
}
@if (ViewBag.Msg != null)
{



    if (ViewBag.Msg == "CreateError")
    {
        <div class="alert alert-warning enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            لا يمكن أن يكون الاسم مكرر، يجب إعادة الإدخال

        </div>
    }

    if (ViewBag.Msg == "DeleteError")
    {
        <div class="alert alert-warning enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            العمليةغير متاحة  ، لا يمكن القيام بعمليةالحذف
        </div>
    }

    if (ViewBag.Msg == "CreateSuccess")
    {
        <div class="alert alert-info enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تمت عملية الإضافة بنجاح
        </div>
    }


    if (ViewBag.Msg == "EditSuccess")
    {
        <div class="alert alert-success enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تمت عملية تعديل البيانات بنجاح
        </div>
    }

    if (ViewBag.Msg == "EditError")
    {
        <div class="alert alert-warning enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            لا يمكن أن يكون الاسم مكرر، يجب إعادة الإدخال

        </div>
    }


    if (ViewBag.Msg == "DeleteSuccess")
    {
        <div class="alert alert-danger enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تمت عملية الحذف بنجاح


        </div>
    }



}
@Html.Partial("_StartView")




<p>
    <button id="btnNewModel" title="إضافة جهةجديدة" class="btn btn-primary">أضافة جهة جديدة</button>
    <button id="btnRefreshModel" title="تحديث المحتوى" class="btn btn-default glyphicon glyphicon-refresh"></button>

</p>
<table id="group" class="table table-striped  table-hover dt" style="text-align:center">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>

           

            <th>
                @Html.DisplayNameFor(model => model.UpdatedAt)
            </th>

           



            <th>
                @Html.DisplayName("العمليات المتاحة")

            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>

           
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedAt)
            </td>

            

            <td>

                <button data-Party-id="@item.Id" title="تعديل" class="js-Edit  btn-xs btn-success "><span class="glyphicon glyphicon-edit"></span></button> 
                <button data-Party-id="@item.Id" title="تفاصيل" class="js-Details  btn-xs btn-default "><span class="glyphicon glyphicon-book"></span></button> 

               @if(CheckDelete.CheckPartydelete(item.Id)==true)
               {

                <button data-Party-id="@item.Id" title="حذف" class="js-delete btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
               }
            </td>
        </tr>


        }

    </tbody>

</table>



@Html.Partial("_LastView")

@* Create Model Start *@
<div class="modal fade" tabindex="-1" id="NewModel"
     data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 id="changeText" class="modal-title">القائمة الفرعية</h4>
            </div>
            <div class="modal-body" id="partialPlaceHolder" style="margin-top:30px">

            </div>
        </div>
    </div>
</div>
@* Create Model End *@


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $("#btnNewModel").on("click", function () {


        $("#changeText").text("إضافة  جهة جديدة");
        var url = '@Url.Action("Create", "Parties")'

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModel').modal('show');
        });

    });

    $("#btnRefreshModel").on("click", function () {

        window.location.replace('@Url.Action("Index", "Parties", new { Id="none"})');


    });




    $("#group").on("click", ".js-Edit", function () {

        $("#changeText").text(" تعديل جهة معينة");

        var url = '@Url.Action("Edit", "Parties")';
        url = url + '/' + $(this).attr("data-Party-id");

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModel').modal('show');
        });

    });

    
    $("#group").on("click", ".js-Details ", function () {

        $("#changeText").text(" تفاصيل جهة معينة");

        var url = '@Url.Action("Details", "Parties")';
        url = url + '/' + $(this).attr("data-Party-id");

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModel').modal('show');
        });

    });



    

    $("#group").on("click", ".js-delete", function () {

        $("#changeText").text("حذف جهة معينة");

        var url = '@Url.Action("Delete", "Parties")';
        url = url + '/' + $(this).attr("data-Party-id") ;

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModel').modal('show');
        });

    });


</script>