ArchiveProject2019/Models/FormGroup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using ArchiveProject2019.Resources;

namespace ArchiveProject2019.Models
{
    public class FormGroup
    {

        [Key]
        public int Id { get; set; }


        [Display(Name = "Is_Active", ResourceType = typeof(main_lang))]
        public bool Is_Active { get; set; }


        [Display(Name = "FormId", ResourceType = typeof(main_lang))]
        public int FormId { get; set; }
        [ForeignKey("FormId")]
        public virtual Form Form { get; set; }


        [Display(Name = "GroupId", ResourceType = typeof(main_lang))]
        public int GroupId { set; get; }
        [ForeignKey("GroupId")]
        public virtual Group Group { get; set; }

        
        [Display(Name = "CreatedAt", ResourceType = typeof(main_lang))]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy-HH:mm:ss}")]
        public string CreatedAt { get; set; }


        //Users Control:
        [Display(Name = "CreatedById", ResourceType = typeof(main_lang))]
        public string CreatedById { set; get; }
        [ForeignKey("CreatedById")]
        public ApplicationUser CreatedBy { set; get; }


        [Display(Name = "UpdatedAt", ResourceType = typeof(main_lang))]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy-HH:mm:ss}")]
        public string Updatedat { get; set; }


        [Display(Name = "UpdatedById", ResourceType = typeof(main_lang))]
        public string UpdatedById { set; get; }
        [ForeignKey("UpdatedById")]
        public ApplicationUser UpdatedBy { set; get; }
    }
}

ArchiveProject2019/Controllers/FormGroupsController.cs
using ArchiveProject2019.HelperClasses;
using ArchiveProject2019.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ArchiveProject2019.Controllers
{
    public class FormGroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();



        
        [AccessDeniedAuthorizeattribute(ActionName = "FormGroupsIndex")]
        public ActionResult Index(int? Id, string msg = "none")
        {

            ViewBag.Current = "Forms";

            if (Id == null)
            {

                return RedirectToAction("BadRequestError", "ErrorController");


            }

            Form form = db.Forms.Find(Id);
            if (form == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");

            }


            if (!msg.Equals("none"))
            {
                ViewBag.Msg = msg;

            }
            else
            {
                ViewBag.Msg = null;
            }
            Session["Form_Id"] = Id;
            var formGroups = db.FormGroups.Where(a => a.FormId == Id).Include(f => f.Group).Include(f => f.Form);
            return View(formGroups.OrderByDescending(a=>a.CreatedAt).ToList());
        }

        // GET: FormDepartments/Details/5


        
        [AccessDeniedAuthorizeattribute(ActionName = "FormGroupsDetails")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");

            }
            FormGroup formGroup = db.FormGroups.Include(a => a.CreatedBy)
             .Include(a => a.Group).Include(a => a.Form).Include(a=>a.UpdatedBy)
                .SingleOrDefault(a => a.Id == id);
            if (formGroup == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");

            }
            return View(formGroup);
        }



        
        [AccessDeniedAuthorizeattribute(ActionName = "FormGroupsCreate")]
        // GET: FormDepartments/Create
        public ActionResult Create(int? Id)
        {
            ViewBag.Current = "Forms";

            if (Id == null)
            {

                return RedirectToAction("BadRequestError", "ErrorController");


            }

            Form form = db.Forms.Find(Id);
            if (form == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");

            }


            Session["Form_Id"] = Id;


            int Form_Id = Convert.ToInt32(Session["Form_Id"]);

            List<int> Group_form = db.FormGroups.Where(a => a.FormId == Form_Id).Select(a => a.GroupId).Distinct().ToList();

            //All Departments Expect current :
            List<int> GroupsId = db.Groups.Select(a => a.Id).Except(Group_form).ToList();
            ViewBag.FormIdValue = Form_Id;


            IEnumerable<Group> Groups = db.Groups.Where(a => GroupsId.Contains(a.Id)).ToList();




            return View(Groups);

        }

        [HttpPost]
        //[ValidateAntiForgeryToken]

        
        [AccessDeniedAuthorizeattribute(ActionName = "FormGroupsCreate")]
        public ActionResult Create(int FormIdValue, List<int> Groups)
        {

            ViewBag.Current = "Forms";

            if (Groups == null)
            {
                return RedirectToAction("Index", new { @id = FormIdValue, @msg = "CreateError" });

            }
            if (ModelState.IsValid)
            {
                List<string> UsersId = new List<string>();
                string NotificationTime = string.Empty;
                string UserId = User.Identity.GetUserId();
                string GroupName = string.Empty;

                Notification notification = null;
                FormGroup formgroup = null;
                foreach (int i in Groups)
                {
                    NotificationTime = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");

                    formgroup = new FormGroup()
                    {

                        GroupId = i,
                        FormId = FormIdValue,
                        Is_Active = true,
                        CreatedAt = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss"),
                        CreatedById = this.User.Identity.GetUserId()

                    };
                    db.FormGroups.Add(formgroup);

                    GroupName = db.Groups.Find(formgroup.GroupId).Name;
                    List<ApplicationUser> Users = db.UsersGroups.Where(a => a.GroupId == i).Include(a=>a.User).Select(a=>a.User).ToList();
                    foreach (ApplicationUser user in Users)
                    {

                        notification = new Notification()
                        {

                            CreatedAt = NotificationTime,
                            Active = false,
                            UserId = user.Id,
                            Message = "تم إضافة نموذج جديد للمجموعة :"+GroupName +"، النموذج: "+ db.Forms.Find(FormIdValue).Name,
                            NotificationOwnerId = UserId
                        };
                        db.Notifications.Add(notification);
                    }

                }
                db.SaveChanges();
                return RedirectToAction("Index", new { @id = FormIdValue, @msg = "CreateSuccess" });

            }



            return RedirectToAction("Index");

        }


        
        [AccessDeniedAuthorizeattribute(ActionName = "FormGroupsEdit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");

            }
            FormGroup formGroup = db.FormGroups.Include(a=>a.Group).Include(a=>a.Form).SingleOrDefault(a=>a.Id==id);
            if (formGroup == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");

            }


            return View(formGroup);
        }

        
        [HttpPost]

        
        [AccessDeniedAuthorizeattribute(ActionName = "FormGroupsEdit")]
        public ActionResult Edit(int Id)
        {
            List<string> UsersId = new List<string>();
            string NotificationTime = string.Empty;
            string UserId = User.Identity.GetUserId();
            string Message = string.Empty;
        
            Notification notification = null;

            FormGroup formGroup = db.FormGroups.Find(Id);
            if (formGroup == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");



            }

            int Form_Id = formGroup.FormId;
            formGroup.Updatedat = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");
            if (formGroup.Is_Active == true)
            {
                formGroup.Is_Active = false;
                Message = "تم الغاء تفعيل النموذج في المجموعة :"+db.Groups.Find(formGroup.GroupId).Name;
            }
            else
            {
                formGroup.Is_Active = true;
                Message = "تم  تفعيل النموذج في المجموعة :" + db.Groups.Find(formGroup.GroupId).Name;

            }

            formGroup.UpdatedById = this.User.Identity.GetUserId();
            db.Entry(formGroup).State = EntityState.Modified;
            db.SaveChanges();

            NotificationTime = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");


            List<ApplicationUser> Users = db.UsersGroups.Where(a => a.GroupId == formGroup.GroupId).Include(a=>a.User).Select(a=>a.User).ToList();
            foreach (ApplicationUser user in Users)
            {

                notification = new Notification()
                {

                    CreatedAt = NotificationTime,
                    Active = false,
                    UserId = user.Id,
                    Message = Message + "، النموذج :" +db.Forms.Find(Form_Id).Name ,
                    NotificationOwnerId = UserId
                };
                db.Notifications.Add(notification);
            }


            db.SaveChanges();
            return RedirectToAction("Index", new { @id = Form_Id, @msg = "EditSuccess" });



        }


        
        [AccessDeniedAuthorizeattribute(ActionName = "FormGroupsDelete")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");

            }
            FormGroup formGroup = db.FormGroups.Include(a => a.Form).Include(a => a.Group).SingleOrDefault(a => a.Id == id);
            if (formGroup == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");

            }
            return View(formGroup);
        }


        
        [AccessDeniedAuthorizeattribute(ActionName = "FormGroupsDelete")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

         //[Notification Informations]:
            //List Of users
            List<string> UsersId = new List<string>();
            //Notification date:
            string NotificationTime = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");
            //Current user who added,deleted,updated:
            string UserId = User.Identity.GetUserId();
            //Form name:
            string FormName = string.Empty;
            //group Name:
            string GroupName = string.Empty;
            //Notification object:
            Notification notification = null;

            //[Delete object]:
            FormGroup formGroup = db.FormGroups.Find(id);

            //Form name && group name:
            FormName = db.Forms.Find(formGroup.FormId).Name;
            GroupName = db.Groups.Find(formGroup.GroupId).Name;

ArchiveProject2019/Views/FormGroups/Create.cshtml
@model IEnumerable<ArchiveProject2019.Models.Group>

@{
    ViewBag.Title = "اضافة المجموعات للنموذج";
    Layout = "~/Views/Shared/_DashBoardLayout.cshtml";
}




@Html.Partial("_StartView")

@using (Html.BeginForm())
{


    <p>

        <a title="عودة لقائمة النماذج" href="@Url.Action("index","Forms")" class="btn btn-warning">عودة لقائمةالنماذج </a>
        
    </p>
    @Html.Hidden("FormIdValue", (int)ViewBag.FormIdValue)
    <table id="form" class="table table-striped  table-hover dt" style="text-align:center">


        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>

                    @Html.DisplayName("اختر المجموعة")
                    
                </th>
            </tr>
        </thead>


        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <input style="width:20px;height:20px;opacity:0.5;vertical-align:middle;cursor:pointer" type="checkbox" name="Groups" value="@item.Id" />
                    </td>
                </tr>
            }
        </tbody>


    </table>

    <div class="form-group">
        <div style="display:inline-block">
            <label>

                <input style="width:20px;height:20px;opacity:0.5;vertical-align:middle;cursor:pointer" id="checkAll" type="checkbox">تحديدالكل/عدم تحديد

            </label>
        </div>
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="إضافة المجموعات للنموذج" />
        </div>
    </div>
}

@Html.Partial("_LastView")



@section Scripts {

    <script>


                $(document).ready(function () {


                    $("#checkAll").click(function () {

                        $("input[name='Groups']").prop("checked", this.checked);


                        $("input[name='Groups']").click(function () {


                            if ($("input[name='Groups']").length == $("input[name='Groups']:checked").length) {
                                $("#checkAll").prop("checked", "checked");
                            }
                            else {
                                $("#checkAll").removeAttr("checked");

                            }

                        });


                    });









                });

    </script>
    @*@Scripts.Render("~/bundles/jqueryval")*@
}

ArchiveProject2019/Views/FormGroups/Delete.cshtml
@model ArchiveProject2019.Models.FormGroup

@{
    ViewBag.Title = "إزالة المجموعة ";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<h3>هل أنت متأكد من عملية إزالة المجموعة من النموذج ؟</h3>
<div>

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.FormId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Form.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Is_Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Is_Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>




        <dt>
            @Html.DisplayNameFor(model => model.Updatedat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updatedat)
        </dd>



    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="modal-footer justify-content-center" style="margin-top:50px">

            <input title="ازالة المجموعة من النموذج" type="submit" value=" إزالة المجموعة" class="btn btn-danger" />
            <button title="اغلاق النافذة" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
        </div>

    }
</div>

ArchiveProject2019/Views/FormGroups/Details.cshtml
@model ArchiveProject2019.Models.FormGroup

@{
    ViewBag.Title = "تفاصيل المجموعة ";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



<div>

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.FormId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Form.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Is_Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Is_Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.CreatedById)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy.FullName)
        </dd>




        <dt>
            @Html.DisplayNameFor(model => model.Updatedat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updatedat)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.UpdatedById)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy.FullName)
        </dd>




    </dl>


    <div class="modal-footer justify-content-center" style="margin-top:50px">


        <button type="button" title="اغلاق النافذة" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
    </div>


</div>

ArchiveProject2019/Views/FormGroups/Edit.cshtml
@model ArchiveProject2019.Models.FormGroup

@{
    ViewBag.Title = "تعديل المجموعة ";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



<div>

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.FormId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Form.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Is_Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Is_Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>






        <dt>
            @Html.DisplayNameFor(model => model.Updatedat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updatedat)
        </dd>






    </dl>

    @using (Html.BeginForm())
    {

        @Html.HiddenFor(a => Model.Id)


        <div class="modal-footer justify-content-center" style="margin-top:50px">
            <input type="submit" value=" تعديل حالةالتفعيل " class="btn btn-success" />


            <button type="button" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
        </div>
    }



</div>

ArchiveProject2019/Views/FormGroups/Index.cshtml
@model IEnumerable<ArchiveProject2019.Models.FormGroup>

@{
    ViewBag.Title = "إعدادات نماذج المجموعات";
    Layout = "~/Views/Shared/_DashBoardLayout.cshtml";
}



@if (ViewBag.Msg != null)
{



    if (ViewBag.Msg == "CreateError")
    {
        <div class="alert alert-warning enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            لم يتم إضافة أي مجموعة للنموذج، يرجى تحديد مجموعات

        </div>
    }



    if (ViewBag.Msg == "CreateSuccess")
    {
        <div class="alert alert-info enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تمت عملية الإضافة بنجاح
        </div>
    }


    if (ViewBag.Msg == "EditSuccess")
    {
        <div class="alert alert-success enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تمت عملية تعديل حالة التفعيل بنجاح
        </div>
    }




    if (ViewBag.Msg == "DeleteSuccess")
    {
        <div class="alert alert-danger enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تمت عملية إزالةالقسم من النموذج بنجاح


        </div>
    }



}


@Html.Partial("_StartView")



<p>
    <a title="عودة لقائمة النماذج" href="@Url.Action("index","Forms")" class="btn btn-warning">عودة لقائمةالنماذج </a>

    <button id="btnRefreshModel" title="تحديث المحتوى" class="btn btn-default glyphicon glyphicon-refresh"></button>

</p>
<table id="form" class="table table-striped table-hover dt" style="text-align:center">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Form.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Is_Active)
            </th>


            <th>
                @Html.DisplayNameFor(model => model.Updatedat)
            </th>

            <th>
                @Html.DisplayName("العمليات المتاحة")



            </th>
        </tr>

    </thead>
    <tbody>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Group.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Form.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Is_Active)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Updatedat)
                </td>

                <td>
                    <button data-form-id="@item.Id" title="تعديل التفعيل" class="js-active btn-xs btn-success"><span class="glyphicon glyphicon-check"></span></button>
                    <button data-form-id="@item.Id" title="إزالة المجموعة" class="js-delete btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
                    <button data-form-id="@item.Id" title=" تفاصيل اسناد المجموعة للنموذج" class="js-details btn-xs btn-default"><span class="glyphicon glyphicon-book"></span></button>

                </td>
            </tr>
        }
    </tbody>



</table>


@Html.Partial("_LastView")


@* Create Model Start *@
<div class="modal fade" tabindex="-1" id="NewModal"
     data-keyboard="true" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 id="changeText" class="modal-title">القائمة الفرعية</h4>
            </div>
            <div class="modal-body" id="partialPlaceHolder" style="margin-top:30px">

            </div>
        </div>
    </div>
</div>
@* Create Model End *@


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>




      $("#btnRefreshModel").on("click", function () {

                       window.location.replace('@Url.Action("Index", "FormGroups", new { Id = Session["Form_Id"],msg="none" })');


                   });




    $("#form").on("click", ".js-active", function () {
        $("#changeText").text("تعديل حالة التفعيل ");

                       var url = '@Url.Action("Edit", "FormGroups")';
                       url = url + '/' + $(this).attr("data-form-id");

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModal').modal('show');
                       });

                   });

    $("#form").on("click", ".js-delete", function () {

        $("#changeText").text("إزالة مجموعة معين  ");

                       var url = '@Url.Action("Delete", "FormGroups")';
                       url = url + '/' + $(this).attr("data-form-id") ;

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModal').modal('show');
                       });

                   });


        $("#form").on("click", ".js-details", function () {

        $("#changeText").text("تفاصيل اضافة المجموعة للنموذج ");

                       var url = '@Url.Action("Details", "FormGroups")';
                       url = url + '/' + $(this).attr("data-form-id") ;

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModal').modal('show');
                       });

                   });






</script>