ArchiveProject2019/Models/DocumentParty.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using ArchiveProject2019.Resources;

namespace ArchiveProject2019.Models
{
    public class DocumentParty
    {
        [Key]
        public int Id { get; set; }
        

        [Display(Name = "CreatedAt", ResourceType = typeof(main_lang))]
        public string CreatedAt { get; set; }


        [Display(Name = "CreatedById", ResourceType = typeof(main_lang))]
        public string CreatedById { set; get; }
        [ForeignKey("CreatedById")]
        public ApplicationUser CreatedBy { set; get; }


        // Relate with Document Table
        [Display(Name = "DocumentId", ResourceType = typeof(main_lang))]
        [Required(ErrorMessageResourceType = typeof(main_lang), ErrorMessageResourceName = "DocumentRequired")]
        public int DocumentId { get; set; }
        [ForeignKey("DocumentId")]
        public Document Document { get; set; }


        // Relate with Party Table
        [Required(ErrorMessageResourceType = typeof(main_lang), ErrorMessageResourceName = "PartyRequired")]
        [Display(Name = "PartyId", ResourceType = typeof(main_lang))]
        public int PartyId { get; set; }
        [ForeignKey("PartyId")]
        public Party Party { get; set; }
    }
}

ArchiveProject2019/Controllers/DocumentPartiesController.cs
using ArchiveProject2019.HelperClasses;
using ArchiveProject2019.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ArchiveProject2019.Controllers
{
    public class DocumentPartiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        
        [AccessDeniedAuthorizeattribute(ActionName = "DocumentPartyIndex")]

        public ActionResult Index(int? Id, string msg = "none")
        {

            ViewBag.Current = "Document";

            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Document document = db.Documents.Find(Id);
            if (document == null)
            {
                return HttpNotFound();
            }

            if (!msg.Equals("none"))
            {
                ViewBag.Msg = msg;

            }
            else
            {
                ViewBag.Msg = null;
            }
            Session["Document_Id"] = Id;
            var DocumentParties = db.DocumentParties.Where(a => a.DocumentId == Id).Include(f => f.CreatedBy).Include(f => f.Party).Include(f => f.Document);
            return View(DocumentParties.OrderByDescending(a=>a.CreatedAt).ToList());
        }


        
        [AccessDeniedAuthorizeattribute(ActionName = "DocumentPartyCrete")]
        public ActionResult Create(int? Id)
        {
            ViewBag.Current = "Document";

            if (Id == null)
            {

                return RedirectToAction("BadRequestError", "ErrorController");


            }

            Document document = db.Documents.Find(Id);
            if (document == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");

            }


            Session["Document_Id"] = Id;


           

            List<int> Group_form = db.DocumentParties.Where(a => a.DocumentId == Id.Value).Select(a => a.PartyId).Distinct().ToList();

            //All Departments Expect current :
            List<int> GroupsId = db.Parties.Select(a => a.Id).Except(Group_form).ToList();
            ViewBag.DocumentIdValue = Id.Value;


            IEnumerable<Party> Parties = db.Parties.Where(a => GroupsId.Contains(a.Id)).ToList();




            return View(Parties);

        }



       [HttpPost]

        
        [AccessDeniedAuthorizeattribute(ActionName = "DocumentPartyCrete")]
        public ActionResult Create(int DocumentIdValue, List<int> Parties)
        {

            ViewBag.Current = "Forms";

            if (Parties == null)
            {
                return RedirectToAction("Index", new { @id = DocumentIdValue, @msg = "CreateError" });

            }
            if (ModelState.IsValid)
            {
                foreach (int i in Parties)
                {
                    var DocumentParty = new DocumentParty()
                    {
                        PartyId = i,
                        DocumentId = DocumentIdValue,
                        CreatedAt = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss"),
                        CreatedById = this.User.Identity.GetUserId()
                    };

                    db.DocumentParties.Add(DocumentParty);
                    db.SaveChanges();
                }

                return RedirectToAction("Index", new { @id = DocumentIdValue, @msg = "CreateSuccess" });
            }

            return RedirectToAction("Index", new { @id = DocumentIdValue});
        }



        
        [AccessDeniedAuthorizeattribute(ActionName = "DocumentPartyDelete")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");
            }
            DocumentParty DocumentParty = db.DocumentParties.Include(a => a.Document).Include(a=>a.CreatedBy).Include(a => a.Party).SingleOrDefault(a => a.Id == id);
            if (DocumentParty == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");

            }
            return View(DocumentParty);
        }

        // POST: FormDepartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]


        
        [AccessDeniedAuthorizeattribute(ActionName = "DocumentPartyDelete")]
        public ActionResult DeleteConfirmed(int id)
        {
            DocumentParty DocumentParty = db.DocumentParties.Find(id);
            db.DocumentParties.Remove(DocumentParty);
            int Document_Id = DocumentParty.DocumentId;
            db.SaveChanges();
            return RedirectToAction("Index", new { @id = Document_Id, @msg = "DeleteSuccess" });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ArchiveProject2019/Views/DocumentParties/Create.cshtml
@model IEnumerable<ArchiveProject2019.Models.Party>

@{
    ViewBag.Title = "اضافة الجهات المستهدفة للوثيقة الصادرة";
    Layout = "~/Views/Shared/_DashBoardLayout.cshtml";
}




@Html.Partial("_StartView")

@using (Html.BeginForm())
{
    <p>
        <a title="عودة لقائمة الوثائق" href="@Url.Action("index","Documents")" class="btn btn-warning">عودة لقائمة الوثائق </a>
        <div style="display:inline-block">
        </div>
    </p>
    @Html.Hidden("DocumentIdValue", (int)ViewBag.DocumentIdValue)
    <table id="form" class="table table-striped table-bordered table-hover dt" style="text-align:center">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayName("اختر الجهة")
                </th>
            </tr>
        </thead>


        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <input style="width:20px;height:20px;opacity:0.5;vertical-align:middle;cursor:pointer" type="checkbox" name="Parties" value="@item.Id" />
                    </td>
                </tr>
            }
        </tbody>


    </table>

    <div class="form-group">
        <label>

            <input style="width:20px;height:20px;opacity:0.5;vertical-align:middle;cursor:pointer" id="checkAll" type="checkbox"> تحديدالكل / عدم تحديد 

        </label>
        <div class="col-md-offset-2 col-md-10">
            <input title="إضافة الجهات المستهدفة" type="submit" class="btn btn-primary" value="إضافة الجهات المستهدفة" />

        </div>
    </div>
}

@Html.Partial("_LastView")



@section Scripts {

    <script>

        $(document).ready(function ()
        {
            $("#checkAll").click(function ()
            {
                $("input[name='Departments']").prop("checked", this.checked);

                $("input[name='Departments']").click(function ()
                {
                    if ($("input[name='Departments']").length == $("input[name='Departments']:checked").length)
                    {
                        $("#checkAll").prop("checked", "checked");
                    }
                    else
                    {
                        $("#checkAll").removeAttr("checked");
                    }
                });
            });
        });

    </script>
    @*@Scripts.Render("~/bundles/jqueryval")*@
}

ArchiveProject2019/Views/DocumentParties/Delete.cshtml
@model ArchiveProject2019.Models.DocumentParty

@{
    ViewBag.Title = "إزالة الجهة المستهدفة ";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<h3>متأكد من اخراج الجهة من الجهات الغير مستهدفة؟</h3>
<div>

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.PartyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Party.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocumentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document.Subject)
        </dd>

     

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>




        <dt>
            @Html.DisplayNameFor(model => model.CreatedById)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy.FullName)
        </dd>



    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="modal-footer justify-content-center" style="margin-top:50px">
            <input type="submit" value=" إزالة الجهة" class="btn btn-danger" />
            <button title="إغلاق النافذة" type="button" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
        </div>
    }
</div>

ArchiveProject2019/Views/DocumentParties/Index.cshtml
@model IEnumerable<ArchiveProject2019.Models.DocumentParty>

@{
    ViewBag.Title = "الجهات المستهدفة";
    Layout = "~/Views/Shared/_DashBoardLayout.cshtml";
}

@Html.Partial("_StartView")





@if (ViewBag.Msg != null)
{



    if (ViewBag.Msg == "CreateError")
    {
        <div class="alert alert-warning enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            لم يتم إضافة أي جهة مستهجفة، يرجى تحديد الجهات

        </div>
    }



    if (ViewBag.Msg == "CreateSuccess")
    {
        <div class="alert alert-info enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تمت عملية الإضافة بنجاح
        </div>
    }




    if (ViewBag.Msg == "DeleteSuccess")
    {
        <div class="alert alert-danger enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تمت عملية ازالة الجهة من الجهات المستهدفة بنجاح


        </div>
    }



}

<p>
    <a title="عودة لقائمة الوثائق" href="@Url.Action("index","Documents")" class="btn btn-warning">عودة لقائمة الوثائق</a>

    <button id="btnRefreshModel" title="تحديث المحتوى" class="btn btn-default glyphicon glyphicon-refresh"></button>

</p>
<table id="form" class="table table-striped table-bordered table-hover dt" style="text-align:center">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PartyId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DocumentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.CreatedById)
            </th>



            <th>
                @Html.DisplayName("العمليات المتاحة")

            </th>
        </tr>

    </thead>
    <tbody>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Party.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Document.Subject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy.FullName)
                </td>
                <td>
                    <button data-form-id="@item.Id" title="إزالة الجهة" class="js-delete btn-xs btn-link"><span class="glyphicon glyphicon-trash"></span></button>
                </td>
            </tr>
        }
    </tbody>
</table>


@Html.Partial("_LastView")


@* Create Model Start *@
<div class="modal fade" tabindex="-1" id="NewModal"
     data-keyboard="true" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 id="changeText" class="modal-title">القائمة الفرعية</h4>
            </div>
            <div class="modal-body" id="partialPlaceHolder" style="margin-top:30px">

            </div>
        </div>
    </div>
</div>
@* Create Model End *@


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>




      $("#btnRefreshModel").on("click", function () {

                       window.location.replace('@Url.Action("Index", "DocumentParties", new { Id = Session["Document_Id"],msg="none" })');


                   });






    $("#form").on("click", ".js-delete", function () {

        $("#changeText").text("إزالة مجموعة معينة");

                       var url = '@Url.Action("Delete", "DocumentParties")';
                       url = url + '/' + $(this).attr("data-form-id") ;

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModal').modal('show');
                       });

                   });








</script>