ArchiveProject2019/Models/PermissionRole.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using ArchiveProject2019.Resources;

namespace ArchiveProject2019.Models
{
    public class PermissionRole
    {
        [Key]
        public int Id { get; set; }



        [Display(Name = "Is_Active", ResourceType = typeof(main_lang))]
        public bool Is_Active { get; set; }



        [Display(Name = "PermissionId", ResourceType = typeof(main_lang))]
        public int PermissionId { get; set; }
        [ForeignKey("PermissionId")]
        public virtual Permission Permission { get; set; }



        [Display(Name = "RoleId", ResourceType = typeof(main_lang))]
        public string RoleId { get; set; }
        [ForeignKey("RoleId")]
        public virtual ApplicationRoles Role { get; set; }



        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy-HH:mm:ss}")]
        [Display(Name = "CreatedAt", ResourceType = typeof(main_lang))]
        public string CreatedAt { get; set; }



        //Users Control:
        [Display(Name = "CreatedById", ResourceType = typeof(main_lang))]
        public string CreatedById { set; get; }
        [ForeignKey("CreatedById")]
        public ApplicationUser CreatedBy { set; get; }



        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy-HH:mm:ss}")]
        [Display(Name = "UpdatedAt", ResourceType = typeof(main_lang))]
        public string Updatedat { get; set; }



        [Display(Name = "UpdatedById", ResourceType = typeof(main_lang))]
        public string UpdatedById { set; get; }
        [ForeignKey("UpdatedById")]
        public ApplicationUser UpdatedBy { set; get; }
    }
}

ArchiveProject2019/Controllers/PermissionRolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ArchiveProject2019.HelperClasses;
using ArchiveProject2019.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ArchiveProject2019.Controllers
{
    public class PermissionRolesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

      
        
        [AccessDeniedAuthorizeattribute(ActionName = "PermissionRolesIndex")]
        public ActionResult Index(string Id,string msg="none")
        {
            ViewBag.Current = "Roles";

            if (Id == null)
            {
                
                return RedirectToAction("BadRequestError", "ErrorController");

            }
            RoleManager<ApplicationRoles> manger= new RoleManager<ApplicationRoles>(new RoleStore<ApplicationRoles>(db));

            ApplicationRoles role = manger.FindById(Id);
            if (role == null)
            {
                
                return RedirectToAction("HttpNotFoundError", "ErrorController");

            }

            if (!msg.Equals("none"))
            {
                ViewBag.Msg = msg;

            }
            else
            {
                ViewBag.Msg = null;
            }

        


            //Role ID:
            Session["Role_Id"] = role.Id;

            //Permission Role Informations:
            var permissionRoles = db.PermissionRoles.Where(a=>a.RoleId.Equals(Id)).Include(p => p.Permission).Include(p => p.Role).Include(a=>a.CreatedBy).Include(a=>a.UpdatedBy);
            return View(permissionRoles.OrderByDescending(a=>a.CreatedAt).ToList());
        }

        
        [AccessDeniedAuthorizeattribute(ActionName = "PermissionRolesDetails")]
        public ActionResult Details(int? id)
        {
            ViewBag.Current = "Roles";

            if (id == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");
            }
            PermissionRole permissionRole = db.PermissionRoles.Find(id);
            if (permissionRole == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");
            }
            return View(permissionRole);
        }

        
        [AccessDeniedAuthorizeattribute(ActionName = "PermissionRolesCreate")]
        public ActionResult Create()
        {
            ViewBag.Current = "Roles";


            if (Session["Role_Id"] == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");

            }
            //Permission For current role:
            string r = Session["Role_Id"].ToString();
            List<int> Role_Permission = db.PermissionRoles.Where(a => a.RoleId.Equals(r)).ToList().Select(a => a.PermissionId).ToList();

            //All permission Expect current role Permission:
            List<int> NPermission = db.Permissions.Where(a=>a.TypeUser==true).Select(a => a.Id).ToList().Except(Role_Permission).ToList();
            ViewBag.RoleId = Session["Role_Id"];

            //Permissions:
            IEnumerable<Permission> Perm = db.Permissions.Where(a=>NPermission.Contains(a.Id));

            return View(Perm);
        }

     
        [HttpPost]

        
        [AccessDeniedAuthorizeattribute(ActionName = "PermissionRolesCreate")]

        public ActionResult Create(string RoleId,List<int>Sel)
        {
            ViewBag.Current = "Roles";

            if (Sel == null)
            {
                return RedirectToAction("Index", new { @id = Session["Role_Id"].ToString(),@msg="CreateError" });

            }


            string RoleName = db.Roles.Find(RoleId).Name;

            foreach(int P_Id in Sel)
            {
                PermissionRole PR = new PermissionRole() {
                    RoleId = RoleId,
                    PermissionId = P_Id,
                    CreatedAt= DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss"),
                    CreatedById=this.User.Identity.GetUserId(),
                    Is_Active=true




            };
                string NotificationTime = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");
                string PermissionName = db.Permissions.Find(P_Id).Name;

                db.PermissionRoles.Add(PR);



                db.SaveChanges();
                string UserId = User.Identity.GetUserId();
                Notification notification = null;


                List<ApplicationUser> Users = db.Users.Where(a => !a.Id.Equals(UserId) && a.RoleName.Equals(RoleName)).ToList();
                foreach (ApplicationUser user in Users)
                {

                    notification = new Notification()
                    {

                        CreatedAt = NotificationTime,
                        Active = false,
                        UserId = user.Id,
                        Message = "تم إضافة صلاحية جديدة : " + PermissionName+" للدور :"+RoleName,
                        NotificationOwnerId = UserId
                    };
                    db.Notifications.Add(notification);
                }
                db.SaveChanges();



            }

            // return View();
            return RedirectToAction("Index", new { @id = Session["Role_Id"].ToString(), @msg = "CreateSuccess" });

        }



        
        [AccessDeniedAuthorizeattribute(ActionName = "PermissionRolesActive")]
        public ActionResult Active(int? id)
        {
            ViewBag.Current = "Roles";

            if (Session["Role_Id"] == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");

            }
            if (id == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");
            }
            PermissionRole permissionRole = db.PermissionRoles.Include(a => a.Role).Include(a=>a.CreatedBy).FirstOrDefault(a=>a.Id==id);
            if (permissionRole == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");
            }
            //اختبار التفعيل من  قبل الشخص نفسه


            return View(permissionRole);
        }

        [HttpPost,ActionName("Active")]
        [ValidateAntiForgeryToken]
        
        [AccessDeniedAuthorizeattribute(ActionName = "PermissionRolesActive")]
        public ActionResult confirm(int id)
        {
            ViewBag.Current = "Roles";
            string ActiveState = "";
            PermissionRole PermissionRole = db.PermissionRoles.Find(id);
            if(PermissionRole.Is_Active==true)
            {
                PermissionRole.Is_Active = false;
                ActiveState = "إلغاء التفعيل";
            }
            else
            {
                PermissionRole.Is_Active = true;
                ActiveState = " إعادةالتفعيل";
            }

            PermissionRole.Updatedat = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");
            PermissionRole.UpdatedById = this.User.Identity.GetUserId();
            db.Entry(PermissionRole).State = EntityState.Modified;



            string Role_ID = Session["Role_Id"].ToString();
            string RoleName = db.Roles.Find(Role_ID).Name;
            string NotificationTime = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");
            string PermissionName = db.Permissions.Find(PermissionRole.PermissionId).Name;

            db.SaveChanges();

            string UserId = User.Identity.GetUserId();
            Notification notification = null;
            List<ApplicationUser> Users = db.Users.Where(a => !a.Id.Equals(UserId) && a.RoleName.Equals(RoleName)).ToList();
            foreach (ApplicationUser user in Users)
            {

                notification = new Notification()
                {

                    CreatedAt = NotificationTime,
                    Active = false,
                    UserId = user.Id,
                    Message = "تمت  عملية  : " + ActiveState + " للصلاحية :" + PermissionName+" للدور :"+RoleName,
                    NotificationOwnerId = UserId
                };
                db.Notifications.Add(notification);
            }
            db.SaveChanges();

            return RedirectToAction("Index", new { @id = Session["Role_Id"].ToString(), @msg = "ActiveSuccess" });


        }
        
        [AccessDeniedAuthorizeattribute(ActionName = "PermissionRolesDelete")]
        public ActionResult Delete(int? id)
        {
            ViewBag.Current = "Roles";

            if (Session["Role_Id"] == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");

            }
            if (id == null)
            {
                return RedirectToAction("BadRequestError", "ErrorController");
            }
            PermissionRole permissionRole = db.PermissionRoles.Find(id);
            if (permissionRole == null)
            {
                return RedirectToAction("HttpNotFoundError", "ErrorController");
            }

            return View(permissionRole);
        }

      
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        
        [AccessDeniedAuthorizeattribute(ActionName = "PermissionRolesDelete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ViewBag.Current = "Roles";

            PermissionRole permissionRole = db.PermissionRoles.Include(a => a.Role).Include(a => a.CreatedBy).FirstOrDefault(a => a.Id == id);
            db.PermissionRoles.Remove(permissionRole);
            db.SaveChanges();
            string NotificationTime = DateTime.Now.ToString("dd/MM/yyyy-HH:mm:ss");
            string Role_ID = Session["Role_Id"].ToString();
            string RoleName = db.Roles.Find(Role_ID).Name;
            string UserId = User.Identity.GetUserId();

ArchiveProject2019/Views/PermissionRoles/Active.cshtml
@model ArchiveProject2019.Models.PermissionRole

@{
    ViewBag.Title = "تفعيل الصلاحية";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



<h3>هل أنت متأكد من تعديل التفعيل؟</h3>
<div>
  
    <dl class="dl-horizontal">
      

        <dt>
            @Html.DisplayNameFor(model => model.PermissionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Permission.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Is_Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Is_Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.CreatedById)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updatedat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updatedat)
        </dd>

       

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="modal-footer justify-content-center" style="margin-top:50px">

            <input title="تعديل حالة التفعيل" type="submit" value=" تعديل الحالة" class="btn btn-success" />
            <button title="اغلاق النافذة"  type="button" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
        </div>

    }
</div>

ArchiveProject2019/Views/PermissionRoles/Create.cshtml
@model IEnumerable<ArchiveProject2019.Models.Permission>
@using ArchiveProject2019.Models
@{
    ViewBag.Title = "اضافةالصلاحيات للأدوار";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}





@using (Html.BeginForm())
{


            <!-- start project list -->

    <div class="form-horizontal">
        <div class="form-group" style="overflow:auto;height:300px">

            @if (Model.Count() == 0)
            {

                <div class="alert alert-warning" style="text-align:center;font-size:larger">
                    <span class="glyphicon glyphicon-bell">

                    </span> لا يوجد أي صلاحيات متوفرة
                </div>
            }



            @foreach (Permission item in Model)
            {
                <div class="col-md-6 col-sm-12 col-xs-12 ">
                    <input style="width:15px;height:15px;opacity:0.5;vertical-align:middle;cursor:pointer" type="checkbox" value="@item.Id" name="Sel" />
                    <label style="">
                        @item.Name
                    </label>
                </div>


            }



        </div>







        <div class="form-group">
            <div class="col-md-6">
                @Html.Hidden("RoleId", (string)ViewBag.RoleId)



@if (Model.Count() != 0)
{

    

    <div style="display:inline-block">
        <label>

            <input style="width:20px;height:20px;opacity:0.5;vertical-align:middle;cursor:pointer" id="checkAll" type="checkbox"> تحديدالكل/عدم تحديد

        </label>
    </div>
}
<br />
               
            
               
            </div>

        </div>



        <div class="modal-footer justify-content-center" style="margin-top:50px">

            <input title="إضافة الصلاحيات للدور" type="submit" value=" إضافةالصلاحيات" class="btn btn-primary" />
            <button title="اغلاق النافذة" type="button" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
        </div>




    </div>
}


@section scripts{
    <script>




    $(document).ready(function () {


        $("#checkAll").click(function () {

            $("input[name='Sel']").prop("checked", this.checked);


            $("input[name='Sel']").click(function () {


                if ($("input[name='Sel']").length == $("input[name='Sel']:checked").length) {
                    $("#checkAll").prop("checked", "checked");
                }
                else {
                    $("#checkAll").removeAttr("checked");

                }

            });


        });

        

    });

    </script>
}

ArchiveProject2019/Views/PermissionRoles/Delete.cshtml
@model ArchiveProject2019.Models.PermissionRole

@{
    ViewBag.Title = "إزالة الصلاحية";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<h3>هل أنت متأكد من عملية إزالة الصلاحية ؟</h3>
<div>

    <dl class="dl-horizontal">
       
        <dt>
            @Html.DisplayNameFor(model => model.PermissionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Permission.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Is_Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Is_Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.CreatedById)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updatedat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updatedat)
        </dd>

       

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="modal-footer justify-content-center" style="margin-top:50px">

            <input title=" ازالة الصلاحية" type="submit" value=" إزالة الصلاحية" class="btn btn-danger" />
            <button title="اغلاق النافذة" type="button" class="btn btn-warning" data-dismiss="modal">إغلاق</button>
        </div>

    }
</div>

ArchiveProject2019/Views/PermissionRoles/Index.cshtml
@model IEnumerable<ArchiveProject2019.Models.PermissionRole>

@{
    ViewBag.Title = "صلاحيات الأدوار";
    Layout = "~/Views/Shared/_DashBoardLayout.cshtml";
}
@if (ViewBag.Msg != null)
{



    if (ViewBag.Msg == "CreateError")
    {
        <div class="alert alert-warning enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            لم يتم إختيار أي صلاحية لإضافتها، يرجى إعادة الإختيار من الصلاحيات المتوفرة

        </div>
    }

    if (ViewBag.Msg == "DeleteError")
    {
        <div class="alert alert-warning enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            العمليةغير متاحة  ، لا يمكن القيام بعمليةالحذف
        </div>
    }

    if (ViewBag.Msg == "CreateSuccess")
    {
        <div class="alert alert-info enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تم إضافة الصلاحيات إلى الدور بنجاح
        </div>
    }


    if (ViewBag.Msg == "ActiveSuccess")
    {
        <div class="alert alert-success enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تمت عمليةتعديل حالة التعديل للصلاحية بنجاح
        </div>
    }

    if (ViewBag.Msg == "EditError")
    {
        <div class="alert alert-warning enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            لا يمكن أن يكون الاسم مكرر، يجب إعادة الإدخال

        </div>
    }


    if (ViewBag.Msg == "DeleteSuccess")
    {
        <div class="alert alert-danger enterRemove" style="text-align:center;font-size:larger">
            <span class="glyphicon glyphicon-bell">

            </span>
            تمت عملية الحذف بنجاح


        </div>
    }



}
@Html.Partial("_StartView")




<p>
    <button title="إضافة الصلاحيات للدور" id="btnNewModel" class="btn btn-primary">أضافة صلاحيات الممكنة للدور</button>

    <a title="عودة لقائمة الأدوار الرئيسية" href="@Url.Action("index","Roles")" class="btn btn-warning">عودة لقائمة الأدوار  </a>
    <button title="تحديث المحتوى" id="btnRefreshModel" class="btn btn-default glyphicon glyphicon-refresh"></button>

</p>
<table id="form" class="table table-striped  table-hover dt" style="text-align:center">


    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoleId)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.PermissionId)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Is_Active)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Updatedat)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.UpdatedById)
            </th>

            <th>
                @Html.DisplayName("العمليات المتاحة")

            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Role.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Permission.Name)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Is_Active)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Updatedat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedBy.FullName)
            </td>



            <td>
                <button data-form-id="@item.Id" title="تعديل التفعيل" class="js-active btn-xs btn-success"><span class="glyphicon glyphicon-check"></span></button>
                <button data-form-id="@item.Id" title="إزالة الصلاحية" class="js-delete btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
            </td>
        </tr>
        }
    </tbody>


</table>
@Html.Partial("_LastView")




@* Create Model Start *@
<div class="modal fade" tabindex="-1" id="NewModal"
     data-keyboard="true" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 id="changeText" class="modal-title">القائمة الفرعية</h4>
            </div>
            <div class="modal-body" id="partialPlaceHolder" style="margin-top:30px">

            </div>
        </div>
    </div>
</div>
@* Create Model End *@




<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $("#btnNewModel").on("click", function () {

        $("#changeText").text("إضافة الصلاحيات للأدوار");
                       var url = '@Url.Action("Create", "PermissionRoles")'

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModal').modal('show');
                       });

                   });

      $("#btnRefreshModel").on("click", function () {

                       window.location.replace('@Url.Action("Index","PermissionRoles",new { Id = Session["Role_Id"],msg="none" })');


                   });




    $("#form").on("click", ".js-active", function () {
        $("#changeText").text("تعديل حقل معين");

                       var url = '@Url.Action("Active", "PermissionRoles")';
                       url = url + '/' + $(this).attr("data-form-id");

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModal').modal('show');
                       });

                   });

    $("#form").on("click", ".js-delete", function () {

        $("#changeText").text("إزالة صلاحية");

                       var url = '@Url.Action("Delete", "PermissionRoles")';
                       url = url + '/' + $(this).attr("data-form-id") ;

        $("#partialPlaceHolder").load(url, function () {
            $('#NewModal').modal('show');
                       });

                   });








</script>